from Bio.Seq import Seq
my_seq = Seq("ATGCGTGTCACACTTGCTACAATAGCCTGGATGGTTTCTTTTGTCTCCAATTATTCACACACAGCAAATATTTTGCCAGATATCGAAAATGAAGATTTCATCAAAGACTGCGTTCGAATCCATAACAAGTTCCGATCAGAGGTGAAACCAACAGCCAGTGATATGCTATACATGACTTGGGACCCAGCACTAGCCCAAATTGCAAAAGCATGGGCCAGCAATTGCCAGTTTTCACATAATACACGGCTGAAGCCACCCCACAAGCTGCACCCAAACTTCACTTCACTGGGAGAGAACATCTGGACTGGGTCTGTGCCCATTTTTTCTGTGTCTTCCGCCATCACAAACTGGTATGACGAAATCCAGGACTATGACTTCAAGACTCGGATATGCAAAAAAGTCTGTGGCCACTACACTCAGGTTGTTTGGGCAGATAGTTACAAAGTTGGCTGCGCAGTTCAATTTTGCCCTAAAGTTTCTGGCTTTGACGCTCTTTCCAATGGAGCACATTTTATATGCAACTACGGACCAGGAGGGAATTACCCAACTTGGCCATATAAGAGAGGAGCCACCTGCAGTGCCTGCCCCAATAATGACAAGTGTTTGGACAATCTCTGTGTTAACCGACAGCGAGACCAAGTCAAACGTTACTACTCTGTTGTATATCCAGGCTGGCCCATATATCCACGTAACAGATACACTTCTCTCTTTCTCATTGTTAATTCAGTAATTCTAATACTGTCTGTTATAATTACCATTTTGGTACAGCACAAGTACCCTAATTTAGTTCTTTTGGAC")
motif1 = my_seq[170:181]
print(motif1)
motif2 = my_seq[136:146]
print(motif2)
print(len(motif1))
print(len(motif2))
from Bio import motifs
instances  = [Seq("CATGACTTGG"),
               Seq("CAGAGGTGAA"),
              ]
m = motifs.create(instances)
print(m)
print(m.counts)
print(m.counts["A"])
print(m.counts["T"])
print(m.counts["C"])
print(m.counts["G"])
